[project]
name = "shaders-wgsl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "wgpu-shadertoy>=0.1.0",
]
